sample_method_names = [
    "com.example.task.TaskService#getAllTasks",
    "com.example.task.TaskService#getTaskById",
    "com.example.task.TaskService#createTask",
    "com.example.task.TaskService#updateTask",
    "com.example.task.TaskService#deleteTask",
    "com.example.user.UserService#getAllUsers",
    "com.example.user.UserService#getUserById",
    "com.example.user.UserService#createUser",
    "com.example.user.UserService#updateUser",
    "com.example.user.UserService#deleteUser",
    "com.example.user.AuthenticationService#login",
    "com.example.user.AuthenticationService#logout",
    "com.example.user.UserService#changePassword",
    "com.example.user.UserService#resetPassword",
    "com.example.task.TaskService#setTaskPriority",
    "com.example.task.TaskService#getTaskByPriority",
    "com.example.task.TaskService#updateTaskPriority",
    "com.example.task.TaskService#removeTaskPriority",
    "com.example.task.TaskService#setTaskDeadline",
    "com.example.task.TaskService#getTasksByDeadline",
    "com.example.task.TaskService#updateTaskDeadline",
    "com.example.task.TaskService#removeTaskDeadline",
    "com.example.task.TaskService#addTaskToCategory",
    "com.example.task.TaskService#getTasksByCategory",
    "com.example.task.TaskService#updateTaskCategory",
    "com.example.task.TaskService#removeTaskFromCategory",
    "com.example.task.TaskService#setTaskProgress",
    "com.example.task.TaskService#getTasksByProgress",
    "com.example.task.TaskService#updateTaskProgress",
    "com.example.task.TaskService#completeTask",
    "com.example.task.NotificationService#sendTaskNotification",
    "com.example.task.NotificationService#getTaskNotifications",
    "com.example.task.NotificationService#updateTaskNotificationSettings",
    "com.example.task.NotificationService#deleteTaskNotification",
    "com.example.task.TaskService#assignTaskToUser",
    "com.example.task.TaskService#getTasksByAssignee",
    "com.example.task.TaskService#updateTaskAssignment",
    "com.example.task.TaskService#removeTaskAssignment"
]


class TestSimilarityFinder:
    def test_execute_with_actual_llm(self):
        pass
